name: argocd-operator-extension
version: latest
helm:
  driver: secret
  maxHistory: 10
logger:
  level: info
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi