name: argocd-operator-extension
version: latest
helm:
  driver: secret
  maxHistory: 10
logger:
  level: info
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
images:
  argocd: argoproj/argocd:v2.0.1
  dex: dexidp/dex:v2.28.1
  redis: redis:5.0.12-alpine