name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make all
      env:
        CGO_ENABLED: 0
        GO111MODULE: on
        GOOS: linux
        GOARCH: amd64

    - name: Test
      run: make test
      env:
        CGO_ENABLED: 0
        GO111MODULE: on
        GOOS: linux
        GOARCH: amd64

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - uses: actions/upload-artifact@v2
      with:
        name: manager
        path: bin/manager
        if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v1

      - uses: actions/download-artifact@v2
        with:
          name: manager

      - run: chmod +x manager

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GHCR_TOKEN }}

      - run: cp build/Dockerfile .

      - name: Build and deploy image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/snorwin/argocd-operator-extension:${{ env.RELEASE_VERSION }}